paths = {
    ".astylerc": "~/",
    ".gitconfig": "~/",
    ".tmux.conf": "~/",
    ".Xdefaults": "~/",
    ".xinitrc": "~/",
    ".zshrc": "~/",
    "i3.conf": "~/.i3/config",
    "qutebrowser.conf": "~/.config/qutebrowser/",
    "qutebrowser_keys.conf": "~/.config/qutebrowser/",
    "resolv.conf": "/etc/",
    "torrc": "/etc/tor/",
    "vimrc": "/etc/",
    #"wpa_supplicant.conf": "/etc/wpa_supplicant/",
}
